set encoding=utf8
syntax on
set t_Co=256
set background=dark

set tabstop=4 "ts=4 设置tab键的宽度为4个空格"
set expandtab "设置tab键为空格替代"

set nocompatible "去掉讨厌的有关vi一致性模式，避免以前版本的一些bug和局限    
set number "显示行号    
set autoindent "vim使用自动对起，也就是把当前行的对起格式应用到下一行；    
set smartindent "依据上面的对起格式，智能的选择对起方式，对于类似C语言编    
set shiftwidth=4 "自动缩进的宽度    
set showmatch "设置匹配模式，类似当输入一个左括号时会匹配相应的那个右括号    
"set cursorline    
set nobackup "当修改文件时不进行自动备份    
" just for encode    
set fileencodings=utf-8,gb2312,gbk,gb18030    
set termencoding=utf-8    
set fileformats=unix    
" set encoding=prc    
set hlsearch    "高亮显示所有匹配    
" set foldmethod 
