
# run: run.o stack.o tempparm.o
# 	c++ stack.o tempparm.o run.o -o runc

# temp: stack.o tempparm.o
# 	c++ stack.o tempparm.o -o temp

friend1: friend1.o
	c++ friend1.o -o friend1

friend2: friend2.o
	c++ friend2.o -o friend2

friend3: friend3.o
	c++ friend3.o -o friend3

.PHONY: clean
clean:
	-rm friend1 friend2 